// Set PLAYWRIGHT_MODULE to an installed Playwright module when running this optional check.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require = createRequire(import.meta.url);
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({headless:true, channel:'msedge'});
try {
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  const page = await context.newPage();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://localhost:5173');
  assert.equal(await page.locator('[aria-current="date"]').count(), 1);
  await page.locator('.day:not(.empty) .add').first().click();
  assert.equal(await page.locator('select').inputValue(), 'Ellers');
  await page.getByLabel('Hva skal du gjøre?').fill('Skrive rapport');
  await page.getByLabel('Kategori', {exact:true}).selectOption('Jobb');
  await page.getByRole('button', {name:'Lagre oppgave'}).click();
  await page.waitForSelector('#editor', {state:'detached'});
  assert.equal(await page.locator('.task.jobb').innerText(), 'Skrive rapport\nJobb');
  await page.reload(); assert.equal(await page.locator('.task').count(), 1);
  const month = await page.locator('#month').innerText();
  await page.getByRole('button', {name:'Neste måned'}).click();
  assert.notEqual(await page.locator('#month').innerText(), month);
  await page.getByRole('button', {name:'I dag',exact:true}).click();
  assert.equal(await page.locator('#month').innerText(), month);
  await page.locator('.day:not(.empty) .add').first().click();
  await page.getByLabel('Hva skal du gjøre?').fill('Må beholdes');
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('quota'); }; });
  await page.getByRole('button', {name:'Lagre oppgave'}).click();
  await page.getByRole('alert').filter({hasText:'ikke lagret'}).waitFor();
  assert.equal(await page.getByLabel('Hva skal du gjøre?').inputValue(), 'Må beholdes');
  page.on('dialog', dialog => dialog.accept());
  await page.getByRole('button', {name:'Avbryt'}).click();
  await page.reload();
  const dayButtons = page.locator('.day:not(.empty) .add');
  await dayButtons.nth(4).click();
  await page.getByRole('button', {name:'Avbryt'}).click();
  assert.equal(await dayButtons.nth(4).evaluate(el => el === document.activeElement), true);
  const other = await context.newPage(); await other.goto('http://localhost:5173');
  await dayButtons.first().click();
  await other.locator('.day:not(.empty) .add').first().click();
  await other.getByLabel('Hva skal du gjøre?').fill('Fra en annen fane');
  await other.getByRole('button', {name:'Lagre oppgave'}).click();
  await other.waitForSelector('#editor', {state:'detached'});
  await page.getByRole('button', {name:'Avbryt'}).click();
  assert.equal(await page.locator('.task').count(), 2);
  await other.evaluate(() => { window.held = navigator.locks.request('smart-todo-save', () => new Promise(resolve => { window.releaseSave = resolve; })); });
  await page.locator('.day:not(.empty) .add').first().click();
  await page.getByLabel('Hva skal du gjøre?').fill('Venter på lagring');
  await page.getByRole('button', {name:'Lagre oppgave'}).click();
  assert.equal(await page.getByRole('button', {name:'Avbryt'}).isDisabled(), true);
  await page.getByRole('button', {name:'Neste måned'}).click();
  assert.equal(await page.locator('#editor').count(), 1);
  await other.evaluate(() => window.releaseSave());
  await page.waitForSelector('#editor', {state:'detached'});
  assert.equal(await page.locator('.task').count(), 3);
  await page.screenshot({path:'app/test-results/calendar.png',fullPage:true});
  const corrupt = await browser.newContext();
  await corrupt.addInitScript(() => localStorage.setItem('smart-todo.v1','{broken'));
  const bad = await corrupt.newPage(); await bad.goto('http://localhost:5173');
  assert.match(await bad.locator('#message').innerText(), /ikke lese/);
  assert.equal(await bad.locator('.add:enabled').count(), 0);
  assert.equal(await bad.evaluate(() => localStorage.getItem('smart-todo.v1')), '{broken');
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: creation, categories, reload, navigation, failed save, corrupt storage, focus restoration, cross-tab refresh, pending-save guard, no JS errors.');
} finally { await browser.close(); }
