import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'});
try {
  const page=await browser.newPage(); const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:5173');
  await page.locator('[aria-current="date"] .add').click();
  const notes='Ta med notater\n</textarea><img src=x onerror="window.unwanted=true">\n<script>window.unwanted=true</script>\nFamilie og skole – æøå';
  await page.getByLabel('Hva skal du gjøre?').fill('Rapport');
  await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).fill(notes);
  await page.getByRole('button',{name:'Lagre oppgave'}).click();
  await page.waitForSelector('#editor',{state:'detached'}); await page.reload();
  await page.locator('.week').getByRole('button',{name:'Rediger Rapport',exact:true}).click();
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).inputValue(),notes);
  assert.equal(await page.evaluate(()=>window.unwanted),undefined);
  await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).fill('Nytt utkast\nLinje to');
  await page.locator('.week').getByRole('checkbox',{name:'Ferdig: Rapport',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.week .completed'));
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).inputValue(),'Nytt utkast\nLinje to');
  await page.evaluate(()=>{window.realWrite=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw new Error('quota');};});
  await page.getByRole('button',{name:'Lagre oppgave'}).click();
  await page.getByRole('alert').filter({hasText:'ikke lagret'}).waitFor();
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).inputValue(),'Nytt utkast\nLinje to');
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).isEnabled(),true);
  await page.evaluate(()=>{Storage.prototype.setItem=window.realWrite;});
  await page.getByRole('button',{name:'Lagre oppgave'}).click();
  await page.waitForSelector('#editor',{state:'detached'});
  await page.locator('.week').getByRole('button',{name:'Rediger Rapport',exact:true}).click();
  await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).fill('');
  await page.getByRole('button',{name:'Lagre oppgave'}).click();
  await page.waitForSelector('#editor',{state:'detached'});await page.reload();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('smart-todo.v1')).tasks[0].description),'');
  const legacy = await page.evaluate(()=>{const data=JSON.parse(localStorage.getItem('smart-todo.v1'));delete data.tasks[0].description;localStorage.setItem('smart-todo.v1',JSON.stringify(data));return data.tasks[0];});
  await page.reload();
  await page.locator('.week').getByRole('button',{name:'Rediger Rapport',exact:true}).click();
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).inputValue(),'');
  await page.getByRole('button',{name:'Lagre oppgave'}).click();
  await page.waitForSelector('#editor',{state:'detached'});
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('smart-todo.v1')).tasks[0]),{...legacy,description:''});
  assert.deepEqual(errors,[]);
  console.log('Description browser checks passed: multiline persistence, safe text, editing, completion draft retention, failed save recovery, clearing.');
} finally {await browser.close();}
