import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,channel:'msedge'});
try {
  const context=await browser.newContext({viewport:{width:1500,height:1100}});
  const page=await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:5173');
  const date=await page.locator('[aria-current="date"]').getAttribute('data-date');
  const untouched={id:'untouched',title:'Annen oppgave',date:'2020-01-01',category:'Jobb',description:'Behold'};
  await page.evaluate(task=>localStorage.setItem('smart-todo.v1',JSON.stringify({version:1,tasks:[task]})),untouched);
  await page.reload();
  const undated=page.locator('#undated-panel');
  const save=async()=>{await page.getByRole('button',{name:'Lagre oppgave',exact:true}).click();await page.waitForSelector('#editor',{state:'detached'});};
  const edit=async()=>undated.getByRole('button',{name:'Rediger Huskeliste',exact:true}).click();
  await page.locator('#undated-toggle').click();
  await page.getByRole('button',{name:'+ Ny oppgave uten dato',exact:true}).click();
  await page.getByLabel('Hva skal du gjøre?',{exact:true}).fill('Huskeliste');
  await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).fill('Dette skal beholdes');
  await page.getByLabel('Kategori',{exact:true}).selectOption('Skole');
  await save();
  const originalId=await undated.locator('.task').getAttribute('data-task-id');
  assert.equal(await undated.locator('.task').count(),1);
  assert.equal(await page.locator('.week .task, #upcoming .task').count(),0);
  await page.reload();await page.locator('#undated-toggle').click();await edit();
  assert.equal(await page.getByLabel('Dato',{exact:true}).inputValue(),'');
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).inputValue(),'Dette skal beholdes');
  await page.getByLabel('Start (valgfritt)',{exact:true}).fill('12:00');
  await page.getByLabel('Slutt (valgfritt)',{exact:true}).fill('13:00');
  await page.getByRole('button',{name:'Lagre oppgave',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Velg en dato'}).waitFor();
  const future=`${Number(date.slice(0,4))+1}-02-12`;
  await page.getByLabel('Dato',{exact:true}).fill(future);await save();
  assert.equal(await page.locator('.week .task').getAttribute('data-task-id'),originalId);
  assert.equal(await page.locator(`.week [data-date="${future}"] .task.skole`).count(),1);
  assert.equal(await undated.locator('.task').count(),0);
  await page.locator('.week').getByRole('button',{name:'Rediger Huskeliste',exact:true}).click();
  await page.getByLabel('Dato',{exact:true}).fill('');
  await page.getByLabel('Start (valgfritt)',{exact:true}).fill('');
  await page.getByLabel('Slutt (valgfritt)',{exact:true}).fill('');await save();
  await undated.getByRole('checkbox').click();
  await page.waitForFunction(()=>document.querySelector('#undated-panel .task').classList.contains('completed'));
  await edit();await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).fill('Utkast under rydding');
  await page.getByRole('button',{name:'Rydd side',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#undated-panel .task'));
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).inputValue(),'Utkast under rydding');await save();
  await page.locator('#completed-toggle').click();
  assert.match(await page.locator('#completed-panel').innerText(),/Uten dato/);
  await page.locator('#completed-panel').getByRole('checkbox').click();
  await undated.locator('.task').waitFor();
  assert.equal(await undated.locator('.task.skole').getAttribute('data-task-id'),originalId);
  await edit();
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).inputValue(),'Utkast under rydding');
  await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).fill('Må ikke mistes');
  await page.evaluate(()=>{window.realWrite=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('quota');};});
  await page.getByRole('button',{name:'Lagre oppgave',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'ikke lagret'}).waitFor();
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).inputValue(),'Må ikke mistes');
  await page.evaluate(()=>{Storage.prototype.setItem=window.realWrite;});await save();
  await page.getByRole('button',{name:'+ Ny oppgave uten dato',exact:true}).click();
  await page.getByLabel('Hva skal du gjøre?',{exact:true}).fill('Nytt utkast');
  await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).fill('Nye detaljer');
  await page.getByLabel('Kategori',{exact:true}).selectOption('Familie');
  await undated.getByRole('checkbox').click();
  await page.waitForFunction(()=>document.querySelector('#undated-panel .task').classList.contains('completed'));
  assert.equal(await page.getByLabel('Hva skal du gjøre?',{exact:true}).inputValue(),'Nytt utkast');
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).inputValue(),'Nye detaljer');
  assert.equal(await page.getByLabel('Kategori',{exact:true}).inputValue(),'Familie');
  page.once('dialog',d=>d.dismiss());
  await page.locator('#next').click();
  assert.equal(await page.getByLabel('Hva skal du gjøre?',{exact:true}).inputValue(),'Nytt utkast');
  await save();
  await edit();await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).fill('Mitt utkast');
  const other=await context.newPage();await other.goto('http://localhost:5173');
  await other.locator('#undated-toggle').click();
  await other.locator('#undated-panel').getByRole('button',{name:'Rediger Huskeliste',exact:true}).click();
  await other.getByLabel('Dato',{exact:true}).fill(date);
  await other.getByRole('button',{name:'Lagre oppgave',exact:true}).click();
  await other.waitForSelector('#editor',{state:'detached'});
  await page.getByRole('button',{name:'Lagre oppgave',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'annen fane'}).waitFor();
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).inputValue(),'Mitt utkast');
  assert.equal(await page.evaluate(id=>JSON.parse(localStorage.getItem('smart-todo.v1')).tasks.find(t=>t.id===id).date,originalId),date);
  await other.locator('.week').getByRole('button',{name:'Rediger Huskeliste',exact:true}).click();
  other.once('dialog',d=>d.accept());await other.getByRole('button',{name:'Slett oppgave',exact:true}).click();
  await other.waitForSelector('#editor',{state:'detached'});
  await page.getByRole('button',{name:'Lagre oppgave',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'annen fane'}).waitFor();
  assert.equal(await page.evaluate(id=>JSON.parse(localStorage.getItem('smart-todo.v1')).tasks.some(t=>t.id===id),originalId),false);
  assert.equal(await page.getByLabel('Beskrivelse (valgfritt)',{exact:true}).inputValue(),'Mitt utkast');
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('smart-todo.v1')).tasks.find(t=>t.id==='untouched')),untouched);
  page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Avbryt',exact:true}).click();
  await page.screenshot({path:'app/test-results/undated.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Undated checks passed: capture, reload, scheduling, date removal, time validation, completion, archive, reopen, draft retention, write failure.');
} finally {await browser.close();}
